export const requests = [
  {
    id: 0,
    status: "p",
    title: "Cambio de calzado",
    date: new Date("2/1/23"),
    employee: "Pedro Oyarzún",
    faena: "S.C. INDUSTRIAL MINERA GEO SINTER LTDA.",
    reason: "Número incorrecto de calzado",
  },
  {
    id: 1,
    status: "p",
    title: "Cambio de guantes",
    date: new Date("3/2/23"),
    employee: "Juan Perez",
    faena: "Faena 1",
    reason: "Elemento de protección personal dañado",
  },
  {
    id: 2,
    status: "p",
    title: "Mantenimiento de equipo",
    date: new Date("4/5/23"),
    employee: "María Sánchez",
    faena: "S.C. INDUSTRIAL MINERA GEO SINTER LTDA.",
    reason: "Fallo en el sistema de enfriamiento",
  },
  {
    id: 3,
    status: "p",
    title: "Solicitud de permiso",
    date: new Date("5/6/23"),
    employee: "Roberto González",
    faena: "Faena 2",
    reason: "Asuntos personales",
  },
  {
    id: 4,
    status: "p",
    title: "Revisión de seguridad",
    date: new Date("6/7/23"),
    employee: "Laura Fernández",
    faena: "S.C. INDUSTRIAL MINERA GEO SINTER LTDA.",
    reason: "Actualización de protocolos",
  },
  {
    id: 5,
    status: "p",
    title: "Cambio de casco",
    date: new Date("7/8/23"),
    employee: "Diego Morales",
    faena: "Faena 3",
    reason: "Casco dañado en accidente",
  },
  {
    id: 6,
    status: "p",
    title: "Pedido de materiales",
    date: new Date("8/9/23"),
    employee: "Carolina Ramírez",
    faena: "S.C. INDUSTRIAL MINERA GEO SINTER LTDA.",
    reason: "Necesidad de nuevos suministros",
  },
  {
    id: 7,
    status: "p",
    title: "Entrenamiento en seguridad",
    date: new Date("9/10/23"),
    employee: "Javier Silva",
    faena: "Faena 4",
    reason: "Cumplimiento de normativas",
  },
  {
    id: 8,
    status: "p",
    title: "Reasignación de tareas",
    date: new Date("10/11/23"),
    employee: "Fernanda Gómez",
    faena: "S.C. INDUSTRIAL MINERA GEO SINTER LTDA.",
    reason: "Optimización de procesos",
  },
  {
    id: 9,
    status: "p",
    title: "Control de calidad",
    date: new Date("11/12/23"),
    employee: "Andrés Martínez",
    faena: "Faena 5",
    reason: "Inspección de productos terminados",
  }]